chnage the build

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,4 +1,3 @@
-
 name: Build Windows Application
 
 on:
@@ -9,7 +8,8 @@ jobs:
     runs-on: windows-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
       - name: Setup Python
         uses: actions/setup-python@v5
@@ -24,20 +24,48 @@ jobs:
           python -m pip install pyinstaller
 
       - name: Install Playwright browser
+        shell: pwsh
         run: |
-          $env:PLAYWRIGHT_BROWSERS_PATH="ms-playwright"
+          $env:PLAYWRIGHT_BROWSERS_PATH="$PWD\ms-playwright"
           python -m playwright install chromium
+
+      - name: Verify required files
+        shell: pwsh
+        run: |
+          Write-Host "Checking tesseract..."
+
+          if (!(Test-Path "tesseract")) {
+            Write-Error "tesseract folder not found"
+            exit 1
+          }
+
+          if (!(Test-Path "tesseract\tesseract.exe")) {
+            Write-Error "tesseract.exe not found"
+            exit 1
+          }
+
+          Write-Host "Tesseract OK"
+
+          Write-Host "Checking Playwright..."
+
+          if (!(Test-Path "ms-playwright")) {
+            Write-Error "ms-playwright folder not found"
+            exit 1
+          }
+
+          Write-Host "Playwright OK"
 
       - name: Build application
         shell: pwsh
         run: |
-          python -m PyInstaller --onedir `
+          python -m PyInstaller --clean --noconfirm --onedir `
             --name Parivahan `
             --add-data "tesseract;tesseract" `
             --add-data "ms-playwright;ms-playwright" `
             main.py
 
       - name: Create ZIP
+        shell: pwsh
         run: |
           Compress-Archive `
             -Path dist/Parivahan/* `
